### ISSUE TITLE
The resolver was unable to cast the parent type to the requested type   

### ISSUE THREAD

**Issue by nirzaf** [microsoft/Graphir#34]
``` 
 "errors": [
    {
      "message": "The resolver parent type of field `Patient.name` is `System.Collections.Generic.KeyValuePair`2[System.String,System.Object]` but the resolver requested the type `Hl7.Fhir.Model.Patient`. The resolver was unable to cast the parent type to the requested type.",
      "path": [
        "Patient",
        0,
        "name"
      ],
      "extensions": {
        "field": "Patient.name",
        "code": "HC0053"
      }
    },
```
Sample Query Tried
```
query patientList {
   Patient(id:"67cbf090-4ddb-4799-99ff-a28abe2740b1"){
     name{
       given
       family
      }
     }
   }
```

Tested on this URL resource https://r4.smarthealthit.org

Data fetching to the data loader without any issues
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/18024930/180977007-7cbeb2e1-9788-4881-98a8-53685ebc318e.png)

Do we have to make any modifications to the resolver?

@pjirsa @i-am-dan @jkarasha @msftgits @mjschanne Please help Thank you

**Comment by pjirsa** [comment]
I also ran into this issue when upgrading from HL7.Fhir.R4 3.8 to 4.0. It appears there are breaking changes in the data models in version 4.0. Please ensure you use version 3.8.
`<PackageReference Include="Hl7.Fhir.R4" Version="3.8.3" />`

**Comment by nirzaf** [comment]
Wow it helped to solve the issue, Thank you @pjirsa
