### ISSUE TITLE
General Practitioner Resolvers are not working 

### ISSUE THREAD

**Issue by nirzaf** [microsoft/Graphir#41]
I could not fetch any practitioner details related to Patient resources. Any solutions? @pjirsa 

![image](https://user-images.githubusercontent.com/18024930/190332069-2cf4e8bc-fd8d-4a4f-b42a-c766c0efebda.png)

**Comment by pjirsa** [comment]
@nirzaf make sure your Patient records in FHIR include a reference to the GeneralPractitioner resource
```
"generalPractitioner": [
  {
      "reference": "Practitioner/00000174-0823-dc8d-0000-00000000e876"
  }
]
```
