### ISSUE TITLE
We are trying to access our FHIR resources from Azure 

### ISSUE THREAD

**Issue by nirzaf** [microsoft/Graphir#44]
We are trying to access our Azure FHIR resources through Azure AD 
Our App registrations details are as follows 

![image](https://user-images.githubusercontent.com/18024930/191711218-9da1fe86-8132-4495-8876-1d530ca0571e.png)

Client App Details 
![image](https://user-images.githubusercontent.com/18024930/191711313-a7e6ab8d-ca2c-4da0-b433-52a35a59e58d.png)

Configured API permission 
![image](https://user-images.githubusercontent.com/18024930/191711395-d00ced9d-8036-4b8f-8ec5-515222bf2a64.png)

App Role 
![image](https://user-images.githubusercontent.com/18024930/191711504-57f28a99-bbfd-4b18-887c-0b6cd4c76adb.png)

Although we followed all the instructions on fetching tokens through Postman as mentioned in the documentation, still we are getting the following error message 

ResponseBody: {"error":"invalid_grant","error_description":"AADSTS65001: The user or administrator has not consented to use the app
lication with ID '898cba89-b86d-4099-a6c3-6cfe502009b3' named 'GraphirAPI-Dev'. Send an interactive authorization request for this user and
 resource.\r\nTrace ID: 4637e900-9b41-414d-b9e4-0c8df37a7a00\r\nCorrelation ID: 0f4d94a6-3fb6-4513-90fc-adfb5cdb98ef\r\nTimestamp: 2022-09-
22 09:00:03Z","error_codes":[65001],"timestamp":"2022-09-22 09:00:03Z","trace_id":"4637e900-9b41-414d-b9e4-0c8df37a7a00","correlation_id":"
0f4d94a6-3fb6-4513-90fc-adfb5cdb98ef","suberror":"consent_required","claims":"{\"access_token\":{\"capolids\":{\"essential\":true,\"values\
":[\"98985d48-5ae5-4b44-b117-c476e5d318b6\"]}}}"}

Please let us know if anyone faces the same issue or known any solutions

**Comment by pjirsa** [comment]
Please validate you are using `HDS-Dev-PostMan` ClientID and Secret to generate token from Postman. It looks like you've already consented to the proper API permissions for that app.
In the appsettings.json for Graphir, you want to configure ClientID and Secret from `GraphirAPI-Dev`.

**Comment by nirzaf** [comment]
Those details are configured properly in appsettings.json file with proper valid data

![image](https://user-images.githubusercontent.com/18024930/191770199-0d07c4db-4cbd-4892-b109-6b7fe9990016.png)

We had a discussion with Azure Tech Support guy on this issue and he said all configurations seems to be correct and said he will get back after a deep analyses

**Comment by nirzaf** [comment]
Response from Microsoft Support Team 
<img width="563" alt="image" src="https://user-images.githubusercontent.com/18024930/192967806-11779864-75b9-4671-8ac6-fa7a2e68e7f8.png">

**Comment by pjirsa** [comment]
Try using the az CLI to get a token for the 'GraphirAPI-Dev' scope. Then manually set that as your bearer token when testing with Postman or Banana Cake Pop. The error message you got suggests that not all of the permissions have been consented to.
```
az account get-access-token --scope api://898cba89-b86d-4099-a6c3-6cfe502009b3/.default
```
You can run this from the bash cloud shell too if you don't have the CLI installed locally.

**Comment by pjirsa** [comment]
We determined that the "Scopes" in "FhirConnection" configuration section must include full scope URI for FHIR API service.
`https://myAHDS.fhir.azurehealthcareapis.com/user_impersonation`
