### ISSUE TITLE
When we have a reference in a resource which can be more than one type of resource...

### ISSUE THREAD

**Issue by nirzaf** [microsoft/Graphir#58]
When we have a reference in a resource which can be more than one type of resource, How we can define the return type in the resolver since we do not know it can be a reference to any type of them 

![image](https://user-images.githubusercontent.com/18024930/193788071-b4daf30a-9d68-41c2-8755-4449213ed251.png)

For example, in Appointment Resource, we have a participant field which can be 
"Patient", "Practitioner", "PractitionerRole", "RelatedPerson", "Device", "HealthcareService", "Location" 

<img width="387" alt="image" src="https://user-images.githubusercontent.com/18024930/193787683-ff2d9c98-b18f-4ce8-a117-4647c2c9d94e.png">

How to define the return type of the resolver in such scenarios?

**Comment by pjirsa** [comment]
The `ResourceReference` coming from FHIR may contain a `type` property. In which case the referenced resource *must* resolve to that type. Otherwise, the type can be inferred from the relative URL of the `reference` property.

see: [ResourceReference](https://hl7.org/fhir/references-definitions.html)

**Comment by pjirsa** [comment]
This issue is addressed and resolved by #59

**Comment by pjirsa** [comment]
Sample of reference schema object using `UnionType`
![image](https://user-images.githubusercontent.com/2207109/195455370-3782c634-5cf8-4420-aad8-d1e07063f779.png)
![image](https://user-images.githubusercontent.com/2207109/195455412-88a553d8-b649-4bff-93e2-87e901da8ba7.png)
Sample query using reference type:
![image](https://user-images.githubusercontent.com/2207109/195455802-a800a01e-6be9-42cf-a716-f4fdfaa33baa.png)

![image](https://user-images.githubusercontent.com/2207109/195455861-0866e1a1-0bea-455e-b3c6-677078826fcc.png)
