### ISSUE TITLE
Unable to cast object of type 'Hl7.Fhir.Model.OperationOutcome' to type 'Hl7.Fhir.Model.Patient'

### ISSUE THREAD

**Issue by ravenugo** [microsoft/Graphir#89]
It works with default Hapi fhir configuration. The moment when we changed it to use Azure FhirService, we were getting this error. This used to work before.

bundle.Entry was having an additional operation outcome entry along with Patients List.  This was the same for all the resources, not just the patient. 

query  {
  PatientList {
    id
  }
}

"message": "Unable to cast object of type 'Hl7.Fhir.Model.OperationOutcome' to type 'Hl7.Fhir.Model.Patient'.",
                "stackTrace": "   at Graphir.API.Services.FhirJsonClient.<>c__4`1.<SearchAsync>b__4_0(EntryComponent p) in C:\\Users\\rvenugopal\\develop\\azure\\Graphir\\Graphir.API\\Services\\FhirJsonClient.cs:line 32\r\n   at System.Linq.Enumerable.SelectListIterator`2.ToList()\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at Graphir.API.Services.FhirJsonClient.SearchAsync[T](String query) in C:\\Users\\rvenugopal\\develop\\azure\\Graphir\\Graphir.API\\Services\\FhirJsonClient.cs:line 0\r\n   at Graphir.API.Services.FhirJsonClient.SearchAsync[T](IList`1 criteria) in C:\\Users\\rvenugopal\\develop\\azure\\Graphir\\Graphir.API\\Services\\FhirJsonClient.cs:line 38\r\n   at Graphir.API.DataLoaders.PatientResolvers.GetPatientListResources(FhirJsonClient client, String family, String given, DateTime birthDate, String generalPractitioner) in C:\\Users\\rvenugopal\\develop\\azure\\Graphir\\Graphir.API\\DataLoaders\\PatientResolvers.cs:line 30\r\n   at HotChocolate.Resolvers.Expressions.ExpressionHelper.AwaitTaskHelper[T](Task`1 task)\r\n   at HotChocolate.Types.Helpers.FieldMiddlewareCompiler.<>c__DisplayClass9_0.<<CreateResolverMiddleware>b__0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Executi
![image (54)](https://user-images.githubusercontent.com/4324799/200624042-122b3272-78ef-467c-9713-a350c1265520.png)
on.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"

**Comment by pjirsa** [comment]
This can happen if there is an error being returned by the API. It will frequently come back as an OperationOutcome entity. 

I will add some error handling in the client to watch out for that.

**Comment by ravenugo** [comment]
We created another Azure fhir instance, pointed to it and same response. bundle.Entry was having an additional operation outcome entry for all resources. When we point to the hapi fhir instanse as configured on appsettings.development.json it works. 

Recommend you to try flipping on your end to Azure Fhir Service "chestist-fhir-api.azure...." and see whether it works. As mentioned this was working before (coudn't recollect which commit could have broken this).

**Comment by pjirsa** [comment]
@nirzaf @ravenugo There was a bug in the request URL construction of the FhirJsonClient. hapiFhir was ignoring the problem. But Azure Health Data Service was returning an error for it. 
The bug has been fixed and exception handling has been added to present more friendly error messages.
